library(sqldf)
getwd()
election <- read.csv("presidential_polls.csv") 
levels(election$state)

clinton <- subset(election,select = c(enddate, adjpoll_clinton))
clintonByMonth<- clinton[order(as.Date(clinton$enddate, format="%m/%d/%Y")),]
clintonTest <- subset(clintonByMonth, select = c(adjpoll_clinton))

clinton1<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '11%15'")
clinton2<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '12%15'")
clinton3<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '1/%16'")
clinton4<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '2%16'")
clinton5<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '3%16'")
clinton6<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '4%16'")
clinton7<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '5%16'")
clinton8<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '6%16'")
clinton9<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '7%16'")
clinton10<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '8%16'")
clinton11<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '9%16'")
clinton12<- sqldf("select sum(adjpoll_clinton) from clinton where enddate like '10%16'")

v <- c(clinton1,clinton2,clinton3,clinton4,clinton5,clinton6,clinton7,clinton8,clinton9,clinton10,clinton11,clinton12)
yourvector <- unlist(v)

trump <- subset(election,select = c(enddate, adjpoll_trump))
trump1<- sqldf("select sum(adjpoll_trump) from trump where enddate like '11%15'")
trump2<- sqldf("select sum(adjpoll_trump) from trump where enddate like '12%15'")
trump3<- sqldf("select sum(adjpoll_trump) from trump where enddate like '1/%16'")
trump4<- sqldf("select sum(adjpoll_trump) from trump where enddate like '2%16'")
trump5<- sqldf("select sum(adjpoll_trump) from trump where enddate like '3%16'")
trump6<- sqldf("select sum(adjpoll_trump) from trump where enddate like '4%16'")
trump7<- sqldf("select sum(adjpoll_trump) from trump where enddate like '5%16'")
trump8<- sqldf("select sum(adjpoll_trump) from trump where enddate like '6%16'")
trump9<- sqldf("select sum(adjpoll_trump) from trump where enddate like '7%16'")
trump10<- sqldf("select sum(adjpoll_trump) from trump where enddate like '8%16'")
trump11<- sqldf("select sum(adjpoll_trump) from trump where enddate like '9%16'")
trump12<- sqldf("select sum(adjpoll_trump) from trump where enddate like '10%16'")

vtrump <- c(trump1,trump2,trump3,trump4,trump5,trump6,trump7,trump8,trump9,trump10,trump11,trump12)
trumpVector <- unlist(vtrump)

johnson <- subset(election,select = c(enddate, adjpoll_johnson ))
johnson1<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '11%15'")
johnson2<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '12%15'")
johnson3<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '1/%16'")
johnson4<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '2%16'")
johnson5<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '3%16'")
johnson6<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '4%16'")
johnson7<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '5%16'")
johnson8<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '6%16'")
johnson9<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '7%16'")
johnson10<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '8%16'")
johnson11<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '9%16'")
johnson12<- sqldf("select sum(adjpoll_johnson ) from johnson  where enddate like '10%16'")

vjohnson  <- c(johnson1,johnson2,johnson3,johnson4,johnson5,johnson6,johnson7,johnson8,johnson9,johnson10,johnson11,johnson12)
johnsonVector <- unlist(vjohnson )

plot(yourvector,col="black",type = "o",xlab = "month",ylab = "Adjpolls")
lines(trumpVector,type="o",col="red")
lines(johnsonVector,type="o",col="blue")


